# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
# the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

x = 0
First = 0
Second = 1
Sum = 0
Next = 0

while Next < 4000000:
    Next = First + Second
    First = Second
    Second = Next
    if Next % 2 == 0:
        Sum = Sum + Next
print(Sum)
